# Default values for registry-helmchart.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

wgServerConfig: |+
    ServerConfig here...
urProxy:
  enabled: false

registry:
  # example: registry.dev.kloudlite.io
  host:
  ingressClassName: ingress-nginx 
  clusterIssuer: cluster-issuer # only if tls is enabled

  secret: # example: registry-secret

  # only if tls is enabled
  tlsEnabled: false
  tls:
  - hosts:
    - # example: '*.dev.kloudlite.io'

  # your s3 setup secrets
  s3:
    enabled: true
    # s3 bucket name
    bucket:
    # s3 bucket region endpoint
    regionEndpoint: 
    # s3 bucket region
    region: 
    # AccessKey and Secret with S3 access
    accessKey: # stringvalue
    secretKey: # stringvalue

# your redis setup secrets and configs
  redis:
    enabled: false
    # redis host, port and password
    host: # example: redis-master.default.svc.cluster.local
    port: # example: 6379
    password: # example: stringvalue


  resources:
    limits:
      cpu: 200m
      memory: 200Mi
    requests:
      cpu: 100m
      memory: 100Mi
